Update 0-transfer_file

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,28 +1,26 @@
 #!/usr/bin/env bash
-# checking for command line arguments
-
-if [ $# -  lt 4 ]; 
+# Checking for command-line argument
+if [ $# -lt 4 ]
 then
-	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-        exit 1
+  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+  exit 1
 fi
 
-# assigning parameters to variable
+# Assigning Arguments to variables
 
 path_to_file=$1
 ip=$2
-username+$2
+username=$3
 path_to_ssh_key=$4
 
-#DISABLING STRICT HOST KEY CHECKING
 
-SCP -0 "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
+# Disabbling Strict Host Key checking
+scp -o "StrictHostKeyChecking no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
 
-
-# checking if the transfer was succesful
-if [ $? -eq 0]
+# Checking if the transfer was successful
+if [ $? -eq 0 ]
 then
-	echo "FILE WAS TRANSFERED SUCESSFULLY"
+  echo "FILE TRANSFER WAS SUCCESSFULL"
 else
-        echo "FILE TRANSFER FAILED"
+  echo "FILE TRANSFER FAILED"
 fi
