server

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,10 +1,28 @@
 #!/usr/bin/env bash
-# transfers a file from a client to a server with scp
+# checking for command line arguments
 
-if [ "$#" -lt 3 ]; then
+if [ $# -  lt 4 ]; 
+then
 	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-elif [ "$#" -lt 4 ]; then
-	scp -o StrictHostKeyChecking=no "$1" "$3@$2":~/
+        exit 1
+fi
+
+# assigning parameters to variable
+
+path_to_file=$1
+ip=$2
+username+$2
+path_to_ssh_key=$4
+
+#DISABLING STRICT HOST KEY CHECKING
+
+SCP -0 "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
+
+
+# checking if the transfer was succesful
+if [ $? -eq 0]
+then
+	echo "FILE WAS TRANSFERED SUCESSFULLY"
 else
-	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2":~/
+        echo "FILE TRANSFER FAILED"
 fi
